# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes ğŸ› 
      labels:
        - semver-major
        - breaking-change
    - title: Exciting New Features ğŸ‰
      labels:
        - semver-minor
        - enhancement
        - feature
    - title: Bug Fixes ğŸ›
      labels:
        - semver-patch
        - bug
        - fix
    - title: Other Changes
      labels:
        - "*"